ToyStore/ToyStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from ToyStore import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('products.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('basket/', include('baskets.urls', namespace='basket')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ToyStore/baskets/urls.py
from django.urls import path

from baskets import views

app_name = 'baskets'

urlpatterns = [
    path('basket_add/', views.basket_add, name='basket_add'),
    path('basket_change/', views.basket_change, name='basket_change'),
    path('basket_remove/', views.basket_remove, name='basket_remove'),
]

ToyStore/main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

ToyStore/products/urls.py
from django.urls import path

from products import views

app_name = 'products'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
]

ToyStore/products/models.py
from django.db import models
from django.urls import reverse


class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='products_images', blank=True, null=True, verbose_name='Изображение')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2, verbose_name='Скидка в %')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категория')

    class Meta:
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('id',)

    def __str__(self):
        return f'{self.name} Кол-во - {self.quantity}'

    # метод для кастомного id
    def display_id(self):
        return f'{self.id:04}'

    def get_absolute_url(self):
        return reverse('catalog:product', kwargs={'product_slug': self.slug})

    def selling_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)
        return self.price

ToyStore/products/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_list_or_404, get_object_or_404

from products.models import Products

from products.utils import query_search


def catalog(request, category_slug=None):
    page = request.GET.get('page', 1)
    with_sale = request.GET.get('with_sale', None)
    orderb = request.GET.get('orderb', None)
    query = request.GET.get('q', None)

    if category_slug == 'All':
        products = Products.objects.all()
    elif query:
        products = query_search(query)
    else:
        products = get_list_or_404(Products.objects.filter(category__slug=category_slug))

    if with_sale:
        products = products.filter(discount__gt=0)
    if orderb and orderb != 'default':
        products = products.order_by(orderb)

    paginator = Paginator(products, 3)
    current_page = paginator.page(int(page))

    context = {
        'title': 'Каталог',
        'products': current_page,
        'slug_url': category_slug
    }
    return render(request, 'products/catalog.html', context)


def product(request, product_slug):
    product = Products.objects.get(slug=product_slug)

    context = {
        'product': product
    }
    return render(request, 'products/product.html', context=context)

ToyStore/products/templates/products/catalog.html
{% extends "base.html" %}
{% load static %}
{% load products_tags %}

{% block modal_basket %}
{% include "includes/basket_button.html" %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="dropdown mb-2">
        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
            Фильтры
        </button>

        <form action="{% if request.GET.q%}{% url 'catalog:search' %}{% else %}{% url 'catalog:index' slug_url %}{% endif %}" method="get" class="dropdown-menu bg-dark"
              data-bs-theme="dark">
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="checkbox" name="with_sale" id="flexCheckDefault" value="on" {% if request.GET.with_sale == 'on' %}checked{% endif %}>
                {% if request.GET.q%}
                <input type="hidden" name="q" value="{{ request.GET.q }}">
                {% endif %}
                <label class="form-check-label" for="flexCheckDefault">
                    Товары по акции
                </label>
            </div>
            <p class="text-white mx-3 mt-3">Сортировать:</p>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="orderb" id="flexRadioDefault1" value="default"
                       {% if not request.GET.orderb or request.GET.orderb == 'default' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault1">
                    По умолчанию
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="orderb" id="flexRadioDefault2" value="price"
                       {% if request.GET.orderb == 'price' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault2">
                    От дешевых к дорогим
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="orderb" id="flexRadioDefault3" value="-price"
                       {% if request.GET.orderb == '-price' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault3">
                    От дорогих к дешевым
                </label>
            </div>
            <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
        </form>
    </div>

    {% if request.GET.q %}
    <h2 class="mt-4">Результаты запроса по поиску {{ request.GET.q }}</h2>
        {% if not products %}
            <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">
            <h3 class="mt-4">По запросу {{ request.GET.q }} ничего не найдено</h3>
        {% endif %}
    {% endif %}
    {% for val in products %}
    <div class="col-lg-4 col-md-6 p-4">
        <div class="card border-secondary rounded">
            {% if val.image %}
            <img src="{{ val.image.url }}" class="card-img-top" alt="{{ val.name }}">
            {% else %}
            <img src="{% static 'deps/images/Not found image.png' %}" class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                <a href="{% url 'catalog:product' val.slug %}">
                    <p class="card-title">
                        {% autoescape off %}
                        {% if val.headline %}
                        {{ val.headline }}
                        {% else %}
                        {{ val.name }}
                        {% endif %}
                        {% endautoescape %}
                    </p>
                </a>
                <p class="card-text text-truncate">
                    {% autoescape off %}
                        {% if val.bodyline|truncatechars:50%}
                        {{ val.bodyline }}
                        {% else %}
                        {{ val.description|truncatechars:50 }}
                        {% endif %}
                        {% endautoescape %}
                </p>
                <p class="product_id">id товара: {{ val.display_id }}</p>
                <div class="d-flex justify-content-between">
                    {% if val.discount %}
                    <p><s>{{ val.price }}</s> руб.</p>
                    <p><strong>{{ val.selling_price }} руб.</strong></p>
                    <span class="badge bg-warning text-dark">Скидка {{ val.discount }} %</span>
                    {% else %}
                    <p><strong>{{ val.price }} руб.</strong></p>
                    {% endif %}
                    <a href="{% url 'basket:basket_add' %}" class="btn add-to-basket"
                    data-product-id="{{ val.id }}">
                        {% csrf_token %}
                        <img class="mx-1" src="{% static 'deps/icons/cart-plus.svg' %}" alt="Catalog Icon"
                             width="32" height="32">
                    </a>
                    <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">
                </div>
            </div>
        </div>
    </div>
    {% endfor %}


</div>
<!-- Пагинация -->

{% if products %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center my-4">
        <div class="border-secondary d-flex">
            <li class="page-item {% if not products.has_previous %}disabled{% endif %}">
                <a class="page-link" href="{% if products.has_previous %}?{% change_params page=products.previous_page_number %}{% else %}#{% endif %}">Назад</a>
            </li>

            {% for page in products.paginator.page_range %}
            {% if page >= products.number|add:-2 and page <= products.number|add:2 %}
            <li class="page-item {% if products.number == page %}active{% endif %}">
                <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
            </li>
            {% endif %}
            {% endfor %}

            <li class="page-item {% if not products.has_next %}disabled{% endif %}">
                <a class="page-link" href="{% if products.has_next %}?{% change_params page=products.next_page_number %}{% else %}#{% endif %}">Вперед</a>
            </li>
        </div>
    </ul>
</nav>
{% endif %}
{% endblock %}

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">digddovalny &copy; Магазин игрушек</p>
    </div>
</footer>
{% endblock %}

ToyStore/products/templates/products/product.html
{% extends "base.html" %}
{% load static %}

{% block modal_basket %}
{% include "includes/basket_button.html" %}
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="card mb-4 border-secondary rounded">
        <div class="row">
            <div class="col-md-4">
                <img src="{{ product.image.url }}"
                     class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
            </div>
            <div class="col-md-4 ">
                <p class="product_id mt-3">id: {{product.display_id}}</p>
            </div>
            <div class="modal fade" id="imageModal1" tabindex="-1"
                 aria-labelledby="imageModal1Label" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="imageModal1Label">{{ product.name }}</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Закрыть"></button>
                        </div>
                        <div class="modal-body">
                            <img src="{{ product.image.url }}"
                                 class="img-fluid" alt="Изображение 1">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <p class="card-text">Цена: <strong> {{ product.selling_price }} руб.</strong></p>
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{ product.description }}</p>
            <a href="{% url 'basket:basket_add' %}" class="btn btn-dark add-to-basket"
               data-product-id="{{ product.id }}">
                {% csrf_token %}
                Добавить в корзину</a>
        </div>
    </div>
</div>
{% endblock %}